# Generated by Django 4.1.3 on 2022-11-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='StoreImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='shop/logo')),
                ('front', models.ImageField(blank=True, upload_to='shop/front')),
                ('inside', models.ImageField(blank=True, upload_to='shop/inside')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companypictures', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
