# Generated by Django 4.1.3 on 2022-11-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options_company_name_storeimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeimages',
            options={'verbose_name': 'Store Image', 'verbose_name_plural': 'Store Images'},
        ),
        migrations.AlterField(
            model_name='storeimages',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='company.company'),
        ),
    ]
